"""Generate LaTeX macros and tables for main_jci.tex from simulation/results/separation/.

Every number quoted in the manuscript's simulation section comes from this script, so the text
cannot drift from the result files. Run after `simulation/src/separation/run.py`.

  python paper/tex/make_separation_tables.py
Outputs: paper/tex/generated/separation_numbers.tex, separation_tables.tex
"""
import json
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.normpath(os.path.join(HERE, "..", "..", "simulation", "results", "separation"))
OUT = os.path.join(HERE, "generated")


def load(name):
    df = pd.read_csv(os.path.join(RES, f"{name}.csv"))
    with open(os.path.join(RES, f"{name}.json")) as fh:
        meta = json.load(fh)
    return df, meta


def f(x, d=3):
    return f"{x:.{d}f}"


def main():
    os.makedirs(OUT, exist_ok=True)
    macros, commits = {}, set()

    costs, m = load("costs"); commits.add(m["git_commit"])
    c = costs[(costs.delta == 0.1) & (costs.n == 100000)].iloc[0]
    macros.update(costUniform=f(c.R_uniform, 1), costOptimal=f(c.R_optimal, 1),
                  costCommon=f(c.R_common_temperature, 1), costCommonTau=f(c.common_tau, 3),
                  costRatioCommonUniform=f(c.R_common_temperature / c.R_uniform, 1))

    finite, m = load("finite"); commits.add(m["git_commit"])
    last = finite[finite.kind == "common_temperature_R"].iloc[-1]
    macros.update(finiteBound=f(finite[finite.kind == "A1_bound"].value.iloc[0], 1),
                  finiteConstant=f(finite[finite.kind == "asymptotic_constant_closed_form"].value.iloc[0], 1),
                  finiteSlope=f(last.local_slope, 3))

    audit, m = load("audit"); commits.add(m["git_commit"])
    mix = audit[audit.check == "B_mixture_temperatures"]
    macros.update(mixtureCost=f(mix.cum_loss.iloc[-1], 2))

    designs, m = load("designs"); commits.add(m["git_commit"])
    boundary, m = load("boundary"); commits.add(m["git_commit"])
    cov5k, m = load("coverage_n1e6_r5000/coverage"); commits.add(m["git_commit"])
    r = cov5k.iloc[0]
    macros.update(covFiveK=f(r.coverage_se_hat, 4), covFiveKmcse=f(r.coverage_mcse, 4),
                  covFiveKseRatio=f(r.se_over_sd, 3))
    b = boundary[(boundary.zeta == 0.75) & (boundary.n == 10000)].iloc[0]
    macros.update(covSmallNtau=f(b.coverage_beta0, 3), smallNtau=f(b.n_tau, 0))

    with open(os.path.join(OUT, "separation_numbers.tex"), "w") as fh:
        fh.write("% generated by make_separation_tables.py; do not edit\n")
        fh.write(f"% result commits: {', '.join(sorted(commits))}\n")
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")

    # Table: exploration designs, estimator runs (common random numbers)
    lines = [r"\begin{tabular}{llrrrrr}", r"\toprule",
             r"$\delta$ & design & RMSE & coverage & MCSE & explored & loss $R_n$ \\", r"\midrule"]
    names = {"uniform": "uniform mixing", "optimal": r"$p\propto g^{-1/2}$ (= context temp.)",
             "common_temperature": "common temperature"}
    for delta in sorted(designs.delta.unique(), reverse=True):
        for key, label in names.items():
            row = designs[(designs.delta == delta) & (designs.design == key)].iloc[0]
            lines.append(f"{delta:.2f} & {label} & {f(row.rmse)} & {f(row.coverage)} & "
                         f"{f(row.coverage_mcse)} & {row.explored:.0f} & {row.cum_loss:.1f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    tab_designs = "\n".join(lines)

    lines = [r"\begin{tabular}{rrrrrrrr}", r"\toprule",
             r"$\zeta$ & $n$ & $n\tau_n$ & reps & RMSE & coverage of $\beta_0$ & MCSE & loss $R_n$ (theory) \\",
             r"\midrule"]
    for _, row in boundary.sort_values(["zeta", "n"]).iterrows():
        lines.append(f"{row.zeta:.2f} & {int(row.n):,} & {row.n_tau:.1f} & {int(row.reps):,} & {f(row.rmse)} & "
                     f"{f(row.coverage_beta0)} & {f(row.coverage_mcse)} & {row.cum_loss:.4f} ({row.cum_loss_pred:.4f}) \\\\")
    lines.append(f"0.60 & 1,000,000 & {r.n_tau:.1f} & {int(r.reps):,} & -- & {f(r.coverage_se_hat)} & "
                 f"{f(r.coverage_mcse)} & -- \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    tab_boundary = "\n".join(lines).replace(",", "{,}")

    with open(os.path.join(OUT, "separation_tables.tex"), "w") as fh:
        fh.write("% generated by make_separation_tables.py; do not edit\n")
        fh.write("\\newcommand{\\tabDesigns}{%\n" + tab_designs + "}\n")
        fh.write("\\newcommand{\\tabBoundary}{%\n" + tab_boundary + "}\n")
    print("wrote", OUT, "commits:", commits)


if __name__ == "__main__":
    main()
